name: first workflow
on:
  push:
    branchs:
      - main
jobs:
  demo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print hello-world
        run: echo "hello-world"    
  demo-jobs2:
    needs: demo-jobs
    runs-on: self-hosted   
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check os
        run: |
          uname -a
          whoami

      - name: create a file
        run: |
          echo "this file was created in action" > demo.txt
          ls -l
      - name: read the file
        run: |
          cat demo.txt        
