name: first workflow
on:
  push:
    branches:
      - main
env:
  MY_NAME: neetesh      
jobs:
  demo-jobs:
    runs-on: self-hosted
    env:
      FROM: indore
    steps:
      
      - name: checkout
        uses: actions/checkout@v4
      
      - name: who are you?
        env:
          MY_JOB: Devops Engineer
        run: |
          echo "Im $MY_NAME and im from $FROM  a $MY_JOB"    
  demo-jobs2:
    needs: demo-jobs
    runs-on: self-hosted-2  
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check os
        run: |
          uname -a
          whoami

      - name: create a file
        run: |
          echo "this file was created action2 $my-name" > demo.txt
          ls -l
      - name: read the file 
        run: |
          cat demo.txt        
